language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t lukondefmwila/dockerized-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true lukondefmwila/dockerized-react-app npm test

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-eu-west-1-776008521384
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
